  window.SUPABASE_URL = "https://vypccrybontwlzqmhvys.supabase.co",
  window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cGNjcnlib250d2x6cW1odnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MTUzODUsImV4cCI6MjA5MDM5MTM4NX0.kqyCEBxEdfxyWFIyYyMfLRPyfjlMCCt-ZEXWUGf61gU",
